name: CS CONTACT
favicon: null
layout_spectrum: 0.92194
typography_spectrum: 0.66034
title: CONTACT US
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b6b7bc'
    - '#ffffff'
    - '#000000'
    - '#f7971e'
    - '#474747'
  brandStrength: 0.75
  lightness: 0.8960750051774085
  saturation: 0.3630813134368509
  rhythmicContrast: 0.3558458676561713
purpose: []
